import {
  PersonaProfile,
  Student,
  AdmissionApplication,
  CourseStructure,
  TimetableSlot,
  AttendanceSummary,
  AttendanceSessionRecord,
  ExaminationMark,
  ResourceUploadItem,
  FeeChallan,
  HostelRoom,
  LibraryBook,
  FacultyMember,
  NoticeCircular,
  DocumentVerification,
  ActiveSession,
  AuditLogEntry,
} from '../types/index.js';

export const seedPersonas: PersonaProfile[] = [
  {
    id: 'user_super_admin',
    name: 'Dr. Aris Thorne',
    role: 'SUPER_ADMIN',
    roleLabel: 'Dean of Information & Technology (System Admin)',
    department: 'Central Administration',
    staffId: 'DIR-001',
    email: 'admin@hogwarduni.ac.in',
    password: 'admin123',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    allowedModules: ['*'],
  },
  {
    id: 'user_student',
    name: 'Aarav Sharma',
    role: 'STUDENT',
    roleLabel: 'Undergraduate Student (Enrollment: 2601031800001)',
    department: 'Computer Science & Engineering',
    staffId: '2601031800001',
    email: '2601031800001@hogwarduni.ac.in',
    password: 'student123',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    allowedModules: [
      'dashboard',
      'academic',
      'timetable',
      'attendance',
      'notifications',
      'fees',
      'hostels',
      'documents',
      'library',
      'examinations',
    ],
  },
  {
    id: 'user_faculty_cse',
    name: 'Dr. P. Sundaram',
    role: 'FAC_MEMBER',
    roleLabel: 'Associate Professor (Faculty Member)',
    department: 'Computer Science & Engineering',
    staffId: 'FAC-099',
    email: 'psundaram.CE@hogwarduni.ac.in',
    password: 'faculty123',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    allowedModules: ['dashboard', 'academic', 'timetable', 'attendance', 'bulk-marks', 'bulk-resources', 'notifications'],
  },
  {
    id: 'user_dean_academics',
    name: 'Prof. Evelyn Vance',
    role: 'DEAN_ACADEMICS',
    roleLabel: 'Dean of Academic Affairs & Admissions',
    department: 'Academic Affairs',
    staffId: 'FAC-014',
    email: 'evance.DA@hogwarduni.ac.in',
    password: 'dean123',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    allowedModules: ['dashboard', 'students', 'admissions', 'academic', 'timetable', 'attendance', 'reports', 'notifications'],
  },
  {
    id: 'user_bursar',
    name: 'Meera Deshmukh',
    role: 'BURSAR_FINANCE',
    roleLabel: 'Chief Financial Officer & Bursar',
    department: 'Finance & Accounts',
    staffId: 'FIN-009',
    email: 'bursar.FIN@hogwarduni.ac.in',
    password: 'finance123',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    allowedModules: ['dashboard', 'fees', 'reports', 'audit', 'notifications'],
  },
  {
    id: 'user_coe',
    name: 'Dr. S. K. Bhattacharya',
    role: 'COE_OFFICER',
    roleLabel: 'Controller of Examinations',
    department: 'Examination Branch',
    staffId: 'COE-002',
    email: 'skbhattacharya.coe@hogwarduni.ac.in',
    password: 'exam123',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    allowedModules: ['dashboard', 'bulk-marks', 'bulk-validation', 'documents', 'reports', 'audit', 'notifications'],
  },
  {
    id: 'user_warden',
    name: 'Col. R. S. Rathore',
    role: 'HOSTEL_WARDEN',
    roleLabel: 'Chief Residential Warden',
    department: 'Hostels & Residential Life',
    staffId: 'HOS-001',
    email: 'warden.HW@hogwarduni.ac.in',
    password: 'warden123',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    allowedModules: ['dashboard', 'hostels', 'notifications'],
  },
  {
    id: 'user_hod_cse',
    name: 'Dr. Rajesh Nair',
    role: 'HOD_CSE',
    roleLabel: 'Head of Department (Computer Science)',
    department: 'Computer Science & Engineering',
    staffId: 'FAC-082',
    email: 'rnair.CE@hogwarduni.ac.in',
    password: 'hod123',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    allowedModules: ['dashboard', 'students', 'academic', 'timetable', 'attendance', 'faculty', 'bulk-resources', 'bulk-marks', 'notifications'],
  },
  {
    id: 'user_student_rep',
    name: 'Ananya Iyer',
    role: 'STUDENT',
    roleLabel: 'Class Representative (Roll: 21CS088)',
    department: 'Computer Science & Engineering',
    staffId: '2301031800160',
    email: '2301031800160@hogwarduni.ac.in',
    password: 'student123',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    allowedModules: ['dashboard', 'academic', 'timetable', 'attendance','hostels', 'notifications'],
  },
];

export const seedStudents: Student[] = [
  {
    id: 'stu_001',
    rollNo: '2601031800001',
    registrationNo: 'REG-2026-00001',
    name: 'Aarav Sharma',
    email: 'aarav.sharma@hogward.edu',
    phone: '+91 98450 12345',
    department: 'Computer Science & Engineering',
    departmentId: 'dept_cs',
    courseCode: 'BTECH-CSE',
    division: 'Division A',
    program: 'B.Tech (Hons)',
    semester: 6,
    batch: '2026-2030',
    gpa: 8.92,
    creditsEarned: 134,
    attendancePercent: 91.4,
    feeStatus: 'CLEARED',
    hostelResident: true,
    hostelRoom: 'Kaveri Hall - B-302',
    status: 'ACTIVE',
    guardianName: 'Dr. Vinod Sharma',
    guardianPhone: '+91 98450 99881',
    bloodGroup: 'O+',
    admissionDate: '2026-08-16',
  },
  {
id: 'stu_002',
rollNo: '2301031800160',
registrationNo: 'REG-2023-98256',
name: 'Ananya Iyer',
email: '2301031800160@hogwarduni.ac.in',
phone: '+91 98765 43210',
department: 'Computer Science & Engineering',
departmentId: 'dept_cs',
courseCode: 'BTECH-CSE',
division: 'Division A',
program: 'B.Tech (Hons)',
semester: 6,
batch: '2023-2027',
gpa: 9.45,
creditsEarned: 138,
attendancePercent: 96.2,
feeStatus: 'CLEARED',
status: 'ACTIVE',
guardianName: 'K. S. Iyer',
guardianPhone: '+91 98765 11223',
bloodGroup: 'A+',
admissionDate: '2023-08-16',
hostelResident: true
},
  {
    id: 'stu_003',
    rollNo: '2301031800161',
    registrationNo: 'REG-2023-98188',
    name: 'Ishaan Verma',
    email: 'ishaan.verma@hogward.edu',
    phone: '+91 98111 22334',
    department: 'Computer Science & Engineering',
    departmentId: 'dept_cs',
    courseCode: 'BTECH-CSE',
    division: 'Division A',
    program: 'B.Tech (Hons)',
    semester: 6,
    batch: '2023-2027',
    gpa: 8.75,
    creditsEarned: 134,
    attendancePercent: 93.0,
    feeStatus: 'CLEARED',
    hostelResident: true,
    hostelRoom: 'Ganga Hall - A-202',
    status: 'ACTIVE',
    guardianName: 'S. K. Verma',
    guardianPhone: '+91 98111 99001',
    bloodGroup: 'B+',
    admissionDate: '2023-08-16',
  },
  {
    id: 'stu_004',
    rollNo: '2301031800162',
    registrationNo: 'REG-2023-98205',
    name: 'Karan Patel',
    email: 'karan.patel@hogward.edu',
    phone: '+91 98980 44556',
    department: 'Computer Science & Engineering',
    departmentId: 'dept_cs',
    courseCode: 'BTECH-CSE',
    division: 'Division A',
    program: 'B.Tech (Hons)',
    semester: 6,
    batch: '2023-2027',
    gpa: 8.35,
    creditsEarned: 130,
    attendancePercent: 86.5,
    feeStatus: 'CLEARED',
    hostelResident: false,
    status: 'ACTIVE',
    guardianName: 'Harish Patel',
    guardianPhone: '+91 98980 11223',
    bloodGroup: 'O+',
    admissionDate: '2023-08-16',
  },
  {
    id: 'stu_005',
    rollNo: '2301031800163',
    registrationNo: 'REG-2023-98226',
    name: 'Sameer Sen',
    email: 'sameer.sen@hogward.edu',
    phone: '+91 98310 77889',
    department: 'Computer Science & Engineering',
    departmentId: 'dept_cs',
    courseCode: 'BTECH-CSE',
    division: 'Division A',
    program: 'B.Tech (Hons)',
    semester: 6,
    batch: '2023-2027',
    gpa: 8.55,
    creditsEarned: 132,
    attendancePercent: 89.2,
    feeStatus: 'CLEARED',
    hostelResident: true,
    hostelRoom: 'Kaveri Hall - B-302',
    status: 'ACTIVE',
    guardianName: 'A. K. Sen',
    guardianPhone: '+91 98310 44556',
    bloodGroup: 'A-',
    admissionDate: '2023-08-16',
  },
  {
    id: 'stu_006',
    rollNo: '2301031800164',
    registrationNo: 'REG-2023-98301',
    name: 'Devansh Kulkarni',
    email: 'devansh.k@hogward.edu',
    phone: '+91 98220 54321',
    department: 'Computer Science & Engineering',
    departmentId: 'dept_cs',
    courseCode: 'BTECH-CSE',
    division: 'Division A',
    program: 'B.Tech (Hons)',
    semester: 6,
    batch: '2023-2027',
    gpa: 6.82,
    creditsEarned: 122,
    attendancePercent: 68.4,
    feeStatus: 'OVERDUE',
    hostelResident: false,
    status: 'PROBATION',
    guardianName: 'P. V. Kulkarni',
    guardianPhone: '+91 98220 00112',
    bloodGroup: 'O-',
    admissionDate: '2023-08-16',
  },
  {
    id: 'stu_007',
    rollNo: '2301031800165',
    registrationNo: 'REG-2023-98310',
    name: 'Pooja Hegde',
    email: 'pooja.h@hogward.edu',
    phone: '+91 98451 22334',
    department: 'Computer Science & Engineering',
    departmentId: 'dept_cs',
    courseCode: 'BTECH-CSE',
    division: 'Division A',
    program: 'B.Tech (Hons)',
    semester: 6,
    batch: '2023-2027',
    gpa: 8.88,
    creditsEarned: 134,
    attendancePercent: 92.5,
    feeStatus: 'CLEARED',
    hostelResident: true,
    hostelRoom: 'Ganga Hall - B-101',
    status: 'ACTIVE',
    guardianName: 'R. Hegde',
    guardianPhone: '+91 98451 99001',
    bloodGroup: 'B+',
    admissionDate: '2023-08-16',
  },
  {
    id: 'stu_008',
    rollNo: '2301031800166',
    registrationNo: 'REG-2023-98315',
    name: 'Vikramaditya Roy',
    email: 'vikram.roy@hogward.edu',
    phone: '+91 98300 44556',
    department: 'Computer Science & Engineering',
    departmentId: 'dept_cs',
    courseCode: 'BTECH-CSE',
    division: 'Division A',
    program: 'B.Tech (Hons)',
    semester: 6,
    batch: '2023-2027',
    gpa: 9.12,
    creditsEarned: 136,
    attendancePercent: 95.0,
    feeStatus: 'CLEARED',
    hostelResident: false,
    status: 'ACTIVE',
    guardianName: 'S. N. Roy',
    guardianPhone: '+91 98300 11223',
    bloodGroup: 'AB+',
    admissionDate: '2023-08-16',
  },
  {
    id: 'stu_009',
    rollNo: '2301031800167',
    registrationNo: 'REG-2023-98322',
    name: 'Sneha Deshmukh',
    email: 'sneha.d@hogward.edu',
    phone: '+91 98230 77889',
    department: 'Computer Science & Engineering',
    departmentId: 'dept_cs',
    courseCode: 'BTECH-CSE',
    division: 'Division A',
    program: 'B.Tech (Hons)',
    semester: 6,
    batch: '2023-2027',
    gpa: 8.65,
    creditsEarned: 132,
    attendancePercent: 91.0,
    feeStatus: 'CLEARED',
    hostelResident: true,
    hostelRoom: 'Ganga Hall - A-105',
    status: 'ACTIVE',
    guardianName: 'V. Deshmukh',
    guardianPhone: '+91 98230 44556',
    bloodGroup: 'A+',
    admissionDate: '2023-08-16',
  },
  {
    id: 'stu_010',
    rollNo: '2301031800168',
    registrationNo: 'REG-2023-98330',
    name: 'Rishi Nambiar',
    email: 'rishi.n@hogward.edu',
    phone: '+91 94460 11223',
    department: 'Computer Science & Engineering',
    departmentId: 'dept_cs',
    courseCode: 'BTECH-CSE',
    division: 'Division B',
    program: 'B.Tech (Hons)',
    semester: 6,
    batch: '2023-2027',
    gpa: 7.94,
    creditsEarned: 128,
    attendancePercent: 84.5,
    feeStatus: 'CLEARED',
    hostelResident: true,
    hostelRoom: 'Kaveri Hall - A-204',
    status: 'ACTIVE',
    guardianName: 'M. Nambiar',
    guardianPhone: '+91 94460 99887',
    bloodGroup: 'O+',
    admissionDate: '2023-08-16',
  },
  {
    id: 'stu_011',
    rollNo: '2301031800169',
    registrationNo: 'REG-2023-98335',
    name: 'Aditya Kashyap',
    email: 'aditya.k@hogward.edu',
    phone: '+91 98101 22334',
    department: 'Computer Science & Engineering',
    departmentId: 'dept_cs',
    courseCode: 'BTECH-CSE',
    division: 'Division B',
    program: 'B.Tech (Hons)',
    semester: 6,
    batch: '2023-2027',
    gpa: 8.25,
    creditsEarned: 130,
    attendancePercent: 88.0,
    feeStatus: 'CLEARED',
    hostelResident: false,
    status: 'ACTIVE',
    guardianName: 'R. K. Kashyap',
    guardianPhone: '+91 98101 99001',
    bloodGroup: 'B-',
    admissionDate: '2023-08-16',
  },
  {
    id: 'stu_012',
    rollNo: '2301031800170',
    registrationNo: 'REG-2023-98342',
    name: 'Nandini Swaminathan',
    email: 'nandini.s@hogward.edu',
    phone: '+91 94440 33445',
    department: 'Computer Science & Engineering',
    departmentId: 'dept_cs',
    courseCode: 'BTECH-CSE',
    division: 'Division B',
    program: 'B.Tech (Hons)',
    semester: 6,
    batch: '2023-2027',
    gpa: 9.38,
    creditsEarned: 138,
    attendancePercent: 97.4,
    feeStatus: 'CLEARED',
    hostelResident: true,
    hostelRoom: 'Ganga Hall - B-205',
    status: 'ACTIVE',
    guardianName: 'T. Swaminathan',
    guardianPhone: '+91 94440 88990',
    bloodGroup: 'O+',
    admissionDate: '2023-08-16',
  },
  {
    id: 'stu_013',
    rollNo: '2301031800171',
    registrationNo: 'REG-2023-98350',
    name: 'Harsh Vardhan',
    email: 'harsh.v@hogward.edu',
    phone: '+91 98711 55667',
    department: 'Computer Science & Engineering',
    departmentId: 'dept_cs',
    courseCode: 'BTECH-CSE',
    division: 'Division B',
    program: 'B.Tech (Hons)',
    semester: 6,
    batch: '2023-2027',
    gpa: 7.42,
    creditsEarned: 124,
    attendancePercent: 78.5,
    feeStatus: 'PARTIAL',
    hostelResident: true,
    hostelRoom: 'Kaveri Hall - B-102',
    status: 'ACTIVE',
    guardianName: 'V. P. Singh',
    guardianPhone: '+91 98711 00112',
    bloodGroup: 'AB+',
    admissionDate: '2023-08-16',
  },
  {
    id: 'stu_014',
    rollNo: '2301031800172',
    registrationNo: 'REG-2023-98358',
    name: 'Ritika Sengupta',
    email: 'ritika.s@hogward.edu',
    phone: '+91 98311 66778',
    department: 'Computer Science & Engineering',
    departmentId: 'dept_cs',
    courseCode: 'BTECH-CSE',
    division: 'Division B',
    program: 'B.Tech (Hons)',
    semester: 6,
    batch: '2023-2027',
    gpa: 8.78,
    creditsEarned: 134,
    attendancePercent: 92.0,
    feeStatus: 'CLEARED',
    hostelResident: false,
    status: 'ACTIVE',
    guardianName: 'D. Sengupta',
    guardianPhone: '+91 98311 22334',
    bloodGroup: 'A+',
    admissionDate: '2023-08-16',
  },
  {
    id: 'stu_015',
    rollNo: '2301031800173',
    registrationNo: 'REG-2023-98365',
    name: 'Abhishek Rao',
    email: 'abhishek.rao@hogward.edu',
    phone: '+91 98490 88990',
    department: 'Computer Science & Engineering',
    departmentId: 'dept_cs',
    courseCode: 'BTECH-CSE',
    division: 'Division B',
    program: 'B.Tech (Hons)',
    semester: 6,
    batch: '2023-2027',
    gpa: 8.15,
    creditsEarned: 130,
    attendancePercent: 87.2,
    feeStatus: 'CLEARED',
    hostelResident: true,
    hostelRoom: 'Kaveri Hall - A-108',
    status: 'ACTIVE',
    guardianName: 'G. Rao',
    guardianPhone: '+91 98490 11223',
    bloodGroup: 'O-',
    admissionDate: '2023-08-16',
  },
  {
    id: 'stu_016',
    rollNo: '2301041800001',
    registrationNo: 'REG-2023-44101',
    name: 'Rohan Mehra',
    email: 'rohan.mehra@hogward.edu',
    phone: '+91 97112 34567',
    department: 'Electronics & Communication',
    departmentId: 'dept_ece',
    courseCode: 'BTECH-ECE',
    division: 'Division A',
    program: 'B.Tech',
    semester: 4,
    batch: '2023-2027',
    gpa: 7.64,
    creditsEarned: 88,
    attendancePercent: 73.5,
    feeStatus: 'PARTIAL',
    hostelResident: false,
    status: 'PROBATION',
    guardianName: 'Sunil Mehra',
    guardianPhone: '+91 97112 88990',
    bloodGroup: 'B+',
    admissionDate: '2023-08-12',
  },
  {
    id: 'stu_017',
    rollNo: '2301041800002',
    registrationNo: 'REG-2023-44105',
    name: 'Pranati Reddy',
    email: 'pranati.r@hogward.edu',
    phone: '+91 98480 55667',
    department: 'Electronics & Communication',
    departmentId: 'dept_ece',
    courseCode: 'BTECH-ECE',
    division: 'Division A',
    program: 'B.Tech',
    semester: 4,
    batch: '2023-2027',
    gpa: 8.62,
    creditsEarned: 92,
    attendancePercent: 91.2,
    feeStatus: 'CLEARED',
    hostelResident: true,
    hostelRoom: 'Ganga Hall - B-303',
    status: 'ACTIVE',
    guardianName: 'B. Reddy',
    guardianPhone: '+91 98480 22334',
    bloodGroup: 'A+',
    admissionDate: '2023-08-12',
  },
  {
    id: 'stu_018',
    rollNo: '2301021800001',
    registrationNo: 'REG-2023-11201',
    name: 'Kavya Pillai',
    email: 'kavya.pillai@hogward.edu',
    phone: '+91 94471 23456',
    department: 'Mechanical Engineering',
    departmentId: 'dept_mech',
    courseCode: 'BTECH-MECH',
    division: 'Division A',
    program: 'B.Tech',
    semester: 4,
    batch: '2023-2027',
    gpa: 8.12,
    creditsEarned: 86,
    attendancePercent: 88.0,
    feeStatus: 'CLEARED',
    hostelResident: true,
    hostelRoom: 'Ganga Hall - B-211',
    status: 'ACTIVE',
    guardianName: 'M. Pillai',
    guardianPhone: '+91 94471 88776',
    bloodGroup: 'AB+',
    admissionDate: '2023-08-20',
  },
  {
    id: 'stu_019',
    rollNo: '2301021800002',
    registrationNo: 'REG-2023-11208',
    name: 'Arjun Namboodiri',
    email: 'arjun.n@hogward.edu',
    phone: '+91 94472 99001',
    department: 'Mechanical Engineering',
    departmentId: 'dept_mech',
    courseCode: 'BTECH-MECH',
    division: 'Division A',
    program: 'B.Tech',
    semester: 4,
    batch: '2023-2027',
    gpa: 7.95,
    creditsEarned: 84,
    attendancePercent: 85.5,
    feeStatus: 'CLEARED',
    hostelResident: false,
    status: 'ACTIVE',
    guardianName: 'K. Namboodiri',
    guardianPhone: '+91 94472 33445',
    bloodGroup: 'O+',
    admissionDate: '2023-08-20',
  },
  {
    id: 'stu_020',
    rollNo: '2301011800001',
    registrationNo: 'REG-2023-01001',
    name: 'Tanvi Joshi',
    email: 'tanvi.j@hogward.edu',
    phone: '+91 98200 44556',
    department: 'Civil Engineering',
    departmentId: 'dept_civil',
    courseCode: 'BTECH-CIVIL',
    division: 'Division A',
    program: 'B.Tech',
    semester: 4,
    batch: '2023-2027',
    gpa: 8.44,
    creditsEarned: 88,
    attendancePercent: 90.0,
    feeStatus: 'CLEARED',
    hostelResident: true,
    hostelRoom: 'Ganga Hall - A-301',
    status: 'ACTIVE',
    guardianName: 'S. Joshi',
    guardianPhone: '+91 98200 11223',
    bloodGroup: 'B+',
    admissionDate: '2023-08-20',
  },
  // ==========================================
  // BATCH 2026 INTAKE: BACHELORS (Level 01)
  // 13-digit format: 26 | 01 | 03 | 18 | 00001..
  // ==========================================
  {
    id: 'stu_021',
    rollNo: '2601031800021',
    registrationNo: 'REG-2026-00021',
    name: 'Aryan Singhania',
    email: 'aryan.s@hogward.edu',
    phone: '+91 98110 00101',
    department: 'Computer Science & Engineering',
    departmentId: 'dept_cs',
    courseCode: 'BTECH-CSE',
    division: 'Division A',
    program: 'B.Tech (Hons)',
    semester: 1,
    batch: '2026-2030',
    gpa: 9.10,
    creditsEarned: 24,
    attendancePercent: 96.0,
    feeStatus: 'CLEARED',
    hostelResident: true,
    hostelRoom: 'Kaveri Hall - A-101',
    status: 'ACTIVE',
    guardianName: 'V. Singhania',
    guardianPhone: '+91 98110 99881',
    bloodGroup: 'O+',
    admissionDate: '2026-08-10',
  },
  {
    id: 'stu_022',
    rollNo: '2601031800002',
    registrationNo: 'REG-2026-00002',
    name: 'Diya Choudhury',
    email: 'diya.c@hogward.edu',
    phone: '+91 98310 00102',
    department: 'Computer Science & Engineering',
    departmentId: 'dept_cs',
    courseCode: 'BTECH-CSE',
    division: 'Division A',
    program: 'B.Tech (Hons)',
    semester: 1,
    batch: '2026-2030',
    gpa: 9.25,
    creditsEarned: 24,
    attendancePercent: 94.5,
    feeStatus: 'CLEARED',
    hostelResident: true,
    hostelRoom: 'Ganga Hall - A-102',
    status: 'ACTIVE',
    guardianName: 'P. Choudhury',
    guardianPhone: '+91 98310 99882',
    bloodGroup: 'A+',
    admissionDate: '2026-08-10',
  },
  {
    id: 'stu_023',
    rollNo: '2601031800003',
    registrationNo: 'REG-2026-00003',
    name: 'Kabir Malhotra',
    email: 'kabir.m@hogward.edu',
    phone: '+91 98100 00103',
    department: 'Computer Science & Engineering',
    departmentId: 'dept_cs',
    courseCode: 'BTECH-CSE',
    division: 'Division A',
    program: 'B.Tech (Hons)',
    semester: 1,
    batch: '2026-2030',
    gpa: 8.70,
    creditsEarned: 24,
    attendancePercent: 91.0,
    feeStatus: 'CLEARED',
    hostelResident: false,
    status: 'ACTIVE',
    guardianName: 'A. Malhotra',
    guardianPhone: '+91 98100 99883',
    bloodGroup: 'B+',
    admissionDate: '2026-08-10',
  },
  {
    id: 'stu_024',
    rollNo: '2601031800004',
    registrationNo: 'REG-2026-00004',
    name: 'Anika Trivedi',
    email: 'anika.t@hogward.edu',
    phone: '+91 98250 00104',
    department: 'Computer Science & Engineering',
    departmentId: 'dept_cs',
    courseCode: 'BTECH-CSE',
    division: 'Division A',
    program: 'B.Tech (Hons)',
    semester: 1,
    batch: '2026-2030',
    gpa: 8.95,
    creditsEarned: 24,
    attendancePercent: 93.5,
    feeStatus: 'CLEARED',
    hostelResident: true,
    hostelRoom: 'Ganga Hall - A-103',
    status: 'ACTIVE',
    guardianName: 'M. Trivedi',
    guardianPhone: '+91 98250 99884',
    bloodGroup: 'O+',
    admissionDate: '2026-08-10',
  },
  {
    id: 'stu_025',
    rollNo: '2601031800005',
    registrationNo: 'REG-2026-00005',
    name: 'Siddharth Menon',
    email: 'siddharth.m@hogward.edu',
    phone: '+91 94470 00105',
    department: 'Computer Science & Engineering',
    departmentId: 'dept_cs',
    courseCode: 'BTECH-CSE',
    division: 'Division A',
    program: 'B.Tech (Hons)',
    semester: 1,
    batch: '2026-2030',
    gpa: 8.40,
    creditsEarned: 24,
    attendancePercent: 88.0,
    feeStatus: 'CLEARED',
    hostelResident: true,
    hostelRoom: 'Kaveri Hall - A-102',
    status: 'ACTIVE',
    guardianName: 'G. Menon',
    guardianPhone: '+91 94470 99885',
    bloodGroup: 'AB+',
    admissionDate: '2026-08-10',
  },
  {
    id: 'stu_026',
    rollNo: '2601031800006',
    registrationNo: 'REG-2026-00006',
    name: 'Ishita Bansal',
    email: 'ishita.b@hogward.edu',
    phone: '+91 98120 00106',
    department: 'Computer Science & Engineering',
    departmentId: 'dept_cs',
    courseCode: 'BTECH-CSE',
    division: 'Division B',
    program: 'B.Tech (Hons)',
    semester: 1,
    batch: '2026-2030',
    gpa: 9.05,
    creditsEarned: 24,
    attendancePercent: 95.0,
    feeStatus: 'CLEARED',
    hostelResident: false,
    status: 'ACTIVE',
    guardianName: 'R. Bansal',
    guardianPhone: '+91 98120 99886',
    bloodGroup: 'B-',
    admissionDate: '2026-08-10',
  },
  {
    id: 'stu_027',
    rollNo: '2601031800007',
    registrationNo: 'REG-2026-00007',
    name: 'Nikhil Saxena',
    email: 'nikhil.s@hogward.edu',
    phone: '+91 98720 00107',
    department: 'Computer Science & Engineering',
    departmentId: 'dept_cs',
    courseCode: 'BTECH-CSE',
    division: 'Division B',
    program: 'B.Tech (Hons)',
    semester: 1,
    batch: '2026-2030',
    gpa: 8.60,
    creditsEarned: 24,
    attendancePercent: 89.0,
    feeStatus: 'CLEARED',
    hostelResident: true,
    hostelRoom: 'Kaveri Hall - B-101',
    status: 'ACTIVE',
    guardianName: 'D. Saxena',
    guardianPhone: '+91 98720 99887',
    bloodGroup: 'A+',
    admissionDate: '2026-08-10',
  },
  {
    id: 'stu_028',
    rollNo: '2601031800008',
    registrationNo: 'REG-2026-00008',
    name: 'Tarun Bhattacharya',
    email: 'tarun.b@hogward.edu',
    phone: '+91 98320 00108',
    department: 'Computer Science & Engineering',
    departmentId: 'dept_cs',
    courseCode: 'BTECH-CSE',
    division: 'Division B',
    program: 'B.Tech (Hons)',
    semester: 1,
    batch: '2026-2030',
    gpa: 8.15,
    creditsEarned: 24,
    attendancePercent: 86.5,
    feeStatus: 'CLEARED',
    hostelResident: false,
    status: 'ACTIVE',
    guardianName: 'S. Bhattacharya',
    guardianPhone: '+91 98320 99888',
    bloodGroup: 'O+',
    admissionDate: '2026-08-10',
  },
  {
    id: 'stu_029',
    rollNo: '2601031800009',
    registrationNo: 'REG-2026-00009',
    name: 'Shruti Hegde',
    email: 'shruti.h@hogward.edu',
    phone: '+91 98455 00109',
    department: 'Computer Science & Engineering',
    departmentId: 'dept_cs',
    courseCode: 'BTECH-CSE',
    division: 'Division B',
    program: 'B.Tech (Hons)',
    semester: 1,
    batch: '2026-2030',
    gpa: 8.85,
    creditsEarned: 24,
    attendancePercent: 92.0,
    feeStatus: 'CLEARED',
    hostelResident: true,
    hostelRoom: 'Ganga Hall - B-102',
    status: 'ACTIVE',
    guardianName: 'N. Hegde',
    guardianPhone: '+91 98455 99889',
    bloodGroup: 'A-',
    admissionDate: '2026-08-10',
  },
  {
    id: 'stu_030',
    rollNo: '2601031800010',
    registrationNo: 'REG-2026-00010',
    name: 'Varun Grover',
    email: 'varun.g@hogward.edu',
    phone: '+91 98115 00110',
    department: 'Computer Science & Engineering',
    departmentId: 'dept_cs',
    courseCode: 'BTECH-CSE',
    division: 'Division B',
    program: 'B.Tech (Hons)',
    semester: 1,
    batch: '2026-2030',
    gpa: 7.80,
    creditsEarned: 24,
    attendancePercent: 82.0,
    feeStatus: 'PARTIAL',
    hostelResident: true,
    hostelRoom: 'Kaveri Hall - B-103',
    status: 'ACTIVE',
    guardianName: 'K. L. Grover',
    guardianPhone: '+91 98115 99890',
    bloodGroup: 'B+',
    admissionDate: '2026-08-10',
  },
  // =========================================================================
  // DEGREE LEVEL 02: MASTERS (M.Tech CSE)
  // Notice: 26 | 02 | 03 | 18 | 00001
  // This demonstrates how level '02' prevents collision with Bachelors '01'
  // on the exact same serial '00001' in the same year, branch, and college!
  // =========================================================================
  {
    id: 'stu_031',
    rollNo: '2602031800001',
    registrationNo: 'REG-2026-M0001',
    name: 'Gaurav Bhatnagar',
    email: 'gaurav.b@hogward.edu',
    phone: '+91 98180 11223',
    department: 'Computer Science & Engineering',
    departmentId: 'dept_cs',
    courseCode: 'MTECH-CSE',
    division: 'Division PG',
    program: 'M.Tech (AI & Distributed Systems)',
    semester: 1,
    batch: '2026-2028',
    gpa: 9.50,
    creditsEarned: 32,
    attendancePercent: 98.0,
    feeStatus: 'CLEARED',
    hostelResident: true,
    hostelRoom: 'PG Scholar Hall - A-101',
    status: 'ACTIVE',
    guardianName: 'V. Bhatnagar',
    guardianPhone: '+91 98180 99001',
    bloodGroup: 'O+',
    admissionDate: '2026-08-05',
  },
  {
    id: 'stu_032',
    rollNo: '2602031800002',
    registrationNo: 'REG-2026-M0002',
    name: 'Pallavi Rao',
    email: 'pallavi.rao@hogward.edu',
    phone: '+91 98491 22334',
    department: 'Computer Science & Engineering',
    departmentId: 'dept_cs',
    courseCode: 'MTECH-CSE',
    division: 'Division PG',
    program: 'M.Tech (AI & Distributed Systems)',
    semester: 1,
    batch: '2026-2028',
    gpa: 9.35,
    creditsEarned: 32,
    attendancePercent: 96.5,
    feeStatus: 'CLEARED',
    hostelResident: true,
    hostelRoom: 'PG Scholar Hall - B-102',
    status: 'ACTIVE',
    guardianName: 'K. Rao',
    guardianPhone: '+91 98491 99002',
    bloodGroup: 'A+',
    admissionDate: '2026-08-05',
  },
  {
    id: 'stu_033',
    rollNo: '2602031800003',
    registrationNo: 'REG-2026-M0003',
    name: 'Manish Tiwari',
    email: 'manish.t@hogward.edu',
    phone: '+91 98260 33445',
    department: 'Computer Science & Engineering',
    departmentId: 'dept_cs',
    courseCode: 'MTECH-CSE',
    division: 'Division PG',
    program: 'M.Tech (Cybersecurity)',
    semester: 1,
    batch: '2026-2028',
    gpa: 8.90,
    creditsEarned: 32,
    attendancePercent: 92.0,
    feeStatus: 'CLEARED',
    hostelResident: false,
    status: 'ACTIVE',
    guardianName: 'B. Tiwari',
    guardianPhone: '+91 98260 99003',
    bloodGroup: 'B+',
    admissionDate: '2026-08-05',
  },
  // =========================================================================
  // DEGREE LEVEL 03: DOCTOR OF PHILOSOPHY (PhD CSE)
  // Notice: 26 | 03 | 03 | 18 | 00001
  // This demonstrates level '03' running independently on the same serial!
  // =========================================================================
  {
    id: 'stu_034',
    rollNo: '2603031800001',
    registrationNo: 'REG-2026-D0001',
    name: 'Samyak Jain',
    email: 'samyak.jain@hogward.edu',
    phone: '+91 98270 44556',
    department: 'Computer Science & Engineering',
    departmentId: 'dept_cs',
    courseCode: 'PHD-CSE',
    division: 'Research Wing',
    program: 'Ph.D in Computer Science',
    semester: 1,
    batch: '2026-2031',
    gpa: 9.80,
    creditsEarned: 40,
    attendancePercent: 99.0,
    feeStatus: 'CLEARED',
    hostelResident: true,
    hostelRoom: 'Fellowship Tower - 401',
    status: 'ACTIVE',
    guardianName: 'Dr. C. L. Jain',
    guardianPhone: '+91 98270 99004',
    bloodGroup: 'O+',
    admissionDate: '2026-07-20',
  },
  {
    id: 'stu_035',
    rollNo: '2603031800002',
    registrationNo: 'REG-2026-D0002',
    name: 'Aishwarya Ramanathan',
    email: 'aishwarya.r@hogward.edu',
    phone: '+91 94441 55667',
    department: 'Computer Science & Engineering',
    departmentId: 'dept_cs',
    courseCode: 'PHD-CSE',
    division: 'Research Wing',
    program: 'Ph.D in Quantum Computing',
    semester: 1,
    batch: '2026-2031',
    gpa: 9.75,
    creditsEarned: 40,
    attendancePercent: 97.5,
    feeStatus: 'CLEARED',
    hostelResident: true,
    hostelRoom: 'Fellowship Tower - 402',
    status: 'ACTIVE',
    guardianName: 'Prof. S. Ramanathan',
    guardianPhone: '+91 94441 99005',
    bloodGroup: 'A+',
    admissionDate: '2026-07-20',
  },
  // ==========================================
  // ECE, MECH, CIVIL & IT Cohort (15 Students)
  // ==========================================
  {
    id: 'stu_036',
    rollNo: '2601041800001',
    registrationNo: 'REG-2026-EC001',
    name: 'Karthik Balakrishnan',
    email: 'karthik.b@hogward.edu',
    phone: '+91 94442 66778',
    department: 'Electronics & Communication',
    departmentId: 'dept_ece',
    courseCode: 'BTECH-ECE',
    division: 'Division A',
    program: 'B.Tech',
    semester: 1,
    batch: '2026-2030',
    gpa: 8.75,
    creditsEarned: 24,
    attendancePercent: 91.5,
    feeStatus: 'CLEARED',
    hostelResident: true,
    hostelRoom: 'Kaveri Hall - C-101',
    status: 'ACTIVE',
    guardianName: 'R. Balakrishnan',
    guardianPhone: '+91 94442 99006',
    bloodGroup: 'B+',
    admissionDate: '2026-08-10',
  },
  {
    id: 'stu_037',
    rollNo: '2601041800002',
    registrationNo: 'REG-2026-EC002',
    name: 'Tanushree Dutta',
    email: 'tanushree.d@hogward.edu',
    phone: '+91 98305 77889',
    department: 'Electronics & Communication',
    departmentId: 'dept_ece',
    courseCode: 'BTECH-ECE',
    division: 'Division A',
    program: 'B.Tech',
    semester: 1,
    batch: '2026-2030',
    gpa: 8.90,
    creditsEarned: 24,
    attendancePercent: 93.0,
    feeStatus: 'CLEARED',
    hostelResident: false,
    status: 'ACTIVE',
    guardianName: 'P. Dutta',
    guardianPhone: '+91 98305 99007',
    bloodGroup: 'O+',
    admissionDate: '2026-08-10',
  },
  {
    id: 'stu_038',
    rollNo: '2601021800001',
    registrationNo: 'REG-2026-ME001',
    name: 'Chirag Somani',
    email: 'chirag.s@hogward.edu',
    phone: '+91 98290 88990',
    department: 'Mechanical Engineering',
    departmentId: 'dept_mech',
    courseCode: 'BTECH-MECH',
    division: 'Division A',
    program: 'B.Tech',
    semester: 1,
    batch: '2026-2030',
    gpa: 8.45,
    creditsEarned: 24,
    attendancePercent: 88.5,
    feeStatus: 'CLEARED',
    hostelResident: true,
    hostelRoom: 'Kaveri Hall - C-202',
    status: 'ACTIVE',
    guardianName: 'M. Somani',
    guardianPhone: '+91 98290 99008',
    bloodGroup: 'AB+',
    admissionDate: '2026-08-10',
  },
  {
    id: 'stu_039',
    rollNo: '2601021800002',
    registrationNo: 'REG-2026-ME002',
    name: 'Anwesha Ghosh',
    email: 'anwesha.g@hogward.edu',
    phone: '+91 98315 99001',
    department: 'Mechanical Engineering',
    departmentId: 'dept_mech',
    courseCode: 'BTECH-MECH',
    division: 'Division A',
    program: 'B.Tech',
    semester: 1,
    batch: '2026-2030',
    gpa: 8.65,
    creditsEarned: 24,
    attendancePercent: 90.0,
    feeStatus: 'CLEARED',
    hostelResident: true,
    hostelRoom: 'Ganga Hall - C-104',
    status: 'ACTIVE',
    guardianName: 'S. Ghosh',
    guardianPhone: '+91 98315 11223',
    bloodGroup: 'A+',
    admissionDate: '2026-08-10',
  },
  {
    id: 'stu_040',
    rollNo: '2601011800001',
    registrationNo: 'REG-2026-CE001',
    name: 'Rahul Khandelwal',
    email: 'rahul.k@hogward.edu',
    phone: '+91 98280 11223',
    department: 'Civil Engineering',
    departmentId: 'dept_civil',
    courseCode: 'BTECH-CIVIL',
    division: 'Division A',
    program: 'B.Tech',
    semester: 1,
    batch: '2026-2030',
    gpa: 8.30,
    creditsEarned: 24,
    attendancePercent: 87.0,
    feeStatus: 'CLEARED',
    hostelResident: false,
    status: 'ACTIVE',
    guardianName: 'N. Khandelwal',
    guardianPhone: '+91 98280 99009',
    bloodGroup: 'B+',
    admissionDate: '2026-08-10',
  },
  {
    id: 'stu_041',
    rollNo: '2601051800001',
    registrationNo: 'REG-2026-IT001',
    name: 'Siddheshwar Prabhu',
    email: 'siddhesh.p@hogward.edu',
    phone: '+91 98205 22334',
    department: 'Information Technology',
    departmentId: 'dept_it',
    courseCode: 'BTECH-IT',
    division: 'Division A',
    program: 'B.Tech',
    semester: 1,
    batch: '2026-2030',
    gpa: 8.92,
    creditsEarned: 24,
    attendancePercent: 94.0,
    feeStatus: 'CLEARED',
    hostelResident: true,
    hostelRoom: 'Kaveri Hall - C-303',
    status: 'ACTIVE',
    guardianName: 'V. Prabhu',
    guardianPhone: '+91 98205 99010',
    bloodGroup: 'O+',
    admissionDate: '2026-08-10',
  },
  {
    id: 'stu_042',
    rollNo: '2601051800002',
    registrationNo: 'REG-2026-IT002',
    name: 'Lavanya Sundaresan',
    email: 'lavanya.s@hogward.edu',
    phone: '+91 94443 33445',
    department: 'Information Technology',
    departmentId: 'dept_it',
    courseCode: 'BTECH-IT',
    division: 'Division A',
    program: 'B.Tech',
    semester: 1,
    batch: '2026-2030',
    gpa: 9.15,
    creditsEarned: 24,
    attendancePercent: 95.5,
    feeStatus: 'CLEARED',
    hostelResident: true,
    hostelRoom: 'Ganga Hall - C-205',
    status: 'ACTIVE',
    guardianName: 'S. Sundaresan',
    guardianPhone: '+91 94443 99011',
    bloodGroup: 'A+',
    admissionDate: '2026-08-10',
  },
  {
    id: 'stu_043',
    rollNo: '2601031800011',
    registrationNo: 'REG-2026-00011',
    name: 'Kunal Singhal',
    email: 'kunal.s@hogward.edu',
    phone: '+91 98116 44556',
    department: 'Computer Science & Engineering',
    departmentId: 'dept_cs',
    courseCode: 'BTECH-CSE',
    division: 'Division C',
    program: 'B.Tech (Hons)',
    semester: 1,
    batch: '2026-2030',
    gpa: 8.55,
    creditsEarned: 24,
    attendancePercent: 89.5,
    feeStatus: 'CLEARED',
    hostelResident: false,
    status: 'ACTIVE',
    guardianName: 'P. Singhal',
    guardianPhone: '+91 98116 99012',
    bloodGroup: 'AB+',
    admissionDate: '2026-08-10',
  },
  {
    id: 'stu_044',
    rollNo: '2601031800012',
    registrationNo: 'REG-2026-00012',
    name: 'Mansi Kothari',
    email: 'mansi.k@hogward.edu',
    phone: '+91 98295 55667',
    department: 'Computer Science & Engineering',
    departmentId: 'dept_cs',
    courseCode: 'BTECH-CSE',
    division: 'Division C',
    program: 'B.Tech (Hons)',
    semester: 1,
    batch: '2026-2030',
    gpa: 8.80,
    creditsEarned: 24,
    attendancePercent: 92.5,
    feeStatus: 'CLEARED',
    hostelResident: true,
    hostelRoom: 'Ganga Hall - C-302',
    status: 'ACTIVE',
    guardianName: 'L. Kothari',
    guardianPhone: '+91 98295 99013',
    bloodGroup: 'O+',
    admissionDate: '2026-08-10',
  },
  {
    id: 'stu_045',
    rollNo: '2601031800013',
    registrationNo: 'REG-2026-00013',
    name: 'Pranav Acharya',
    email: 'pranav.a@hogward.edu',
    phone: '+91 98456 66778',
    department: 'Computer Science & Engineering',
    departmentId: 'dept_cs',
    courseCode: 'BTECH-CSE',
    division: 'Division C',
    program: 'B.Tech (Hons)',
    semester: 1,
    batch: '2026-2030',
    gpa: 8.20,
    creditsEarned: 24,
    attendancePercent: 86.0,
    feeStatus: 'CLEARED',
    hostelResident: true,
    hostelRoom: 'Kaveri Hall - C-404',
    status: 'ACTIVE',
    guardianName: 'V. Acharya',
    guardianPhone: '+91 98456 99014',
    bloodGroup: 'B+',
    admissionDate: '2026-08-10',
  },
  {
    id: 'stu_046',
    rollNo: '2601031800014',
    registrationNo: 'REG-2026-00014',
    name: 'Sanya Mirza',
    email: 'sanya.m@hogward.edu',
    phone: '+91 98117 77889',
    department: 'Computer Science & Engineering',
    departmentId: 'dept_cs',
    courseCode: 'BTECH-CSE',
    division: 'Division C',
    program: 'B.Tech (Hons)',
    semester: 1,
    batch: '2026-2030',
    gpa: 9.30,
    creditsEarned: 24,
    attendancePercent: 96.0,
    feeStatus: 'CLEARED',
    hostelResident: false,
    status: 'ACTIVE',
    guardianName: 'F. Mirza',
    guardianPhone: '+91 98117 99015',
    bloodGroup: 'A-',
    admissionDate: '2026-08-10',
  },
  {
    id: 'stu_047',
    rollNo: '2601031800015',
    registrationNo: 'REG-2026-00015',
    name: 'Yashraj Rathore',
    email: 'yashraj.r@hogward.edu',
    phone: '+91 98296 88990',
    department: 'Computer Science & Engineering',
    departmentId: 'dept_cs',
    courseCode: 'BTECH-CSE',
    division: 'Division C',
    program: 'B.Tech (Hons)',
    semester: 1,
    batch: '2026-2030',
    gpa: 8.68,
    creditsEarned: 24,
    attendancePercent: 90.5,
    feeStatus: 'CLEARED',
    hostelResident: true,
    hostelRoom: 'Kaveri Hall - C-405',
    status: 'ACTIVE',
    guardianName: 'B. S. Rathore',
    guardianPhone: '+91 98296 99016',
    bloodGroup: 'AB-',
    admissionDate: '2026-08-10',
  },
  {
    id: 'stu_048',
    rollNo: '2601031800016',
    registrationNo: 'REG-2026-00016',
    name: 'Meenakshi Sundaram',
    email: 'meenakshi.s@hogward.edu',
    phone: '+91 94444 99001',
    department: 'Computer Science & Engineering',
    departmentId: 'dept_cs',
    courseCode: 'BTECH-CSE',
    division: 'Division C',
    program: 'B.Tech (Hons)',
    semester: 1,
    batch: '2026-2030',
    gpa: 9.42,
    creditsEarned: 24,
    attendancePercent: 97.0,
    feeStatus: 'CLEARED',
    hostelResident: true,
    hostelRoom: 'Ganga Hall - C-308',
    status: 'ACTIVE',
    guardianName: 'N. Sundaram',
    guardianPhone: '+91 94444 11223',
    bloodGroup: 'O+',
    admissionDate: '2026-08-10',
  },
  {
    id: 'stu_049',
    rollNo: '2601031800017',
    registrationNo: 'REG-2026-00017',
    name: 'Tejaswini Patil',
    email: 'tejaswini.p@hogward.edu',
    phone: '+91 98225 11223',
    department: 'Computer Science & Engineering',
    departmentId: 'dept_cs',
    courseCode: 'BTECH-CSE',
    division: 'Division C',
    program: 'B.Tech (Hons)',
    semester: 1,
    batch: '2026-2030',
    gpa: 8.84,
    creditsEarned: 24,
    attendancePercent: 92.0,
    feeStatus: 'CLEARED',
    hostelResident: false,
    status: 'ACTIVE',
    guardianName: 'A. Patil',
    guardianPhone: '+91 98225 99017',
    bloodGroup: 'B+',
    admissionDate: '2026-08-10',
  },
  {
    id: 'stu_050',
    rollNo: '2601031800018',
    registrationNo: 'REG-2026-00018',
    name: 'Omkar Nadkarni',
    email: 'omkar.n@hogward.edu',
    phone: '+91 98206 22334',
    department: 'Computer Science & Engineering',
    departmentId: 'dept_cs',
    courseCode: 'BTECH-CSE',
    division: 'Division C',
    program: 'B.Tech (Hons)',
    semester: 1,
    batch: '2026-2030',
    gpa: 8.48,
    creditsEarned: 24,
    attendancePercent: 88.0,
    feeStatus: 'CLEARED',
    hostelResident: true,
    hostelRoom: 'Kaveri Hall - C-408',
    status: 'ACTIVE',
    guardianName: 'S. Nadkarni',
    guardianPhone: '+91 98206 99018',
    bloodGroup: 'A+',
    admissionDate: '2026-08-10',
  },
];

export const seedAdmissions: AdmissionApplication[] = [
  {
    id: 'adm_2026_001',
    applicationNo: 'APP-2026-8801',
    applicantName: 'Tanya Sengupta',
    email: 'tanya.sen@gmail.com',
    phone: '+91 98301 22334',
    programApplied: 'B.Tech Computer Science & Artificial Intelligence',
    departmentId: 'dept_cs',
    entranceScore: 98.4,
    qualifyingPercentage: 96.8,
    status: 'OFFER_ACCEPTED',
    category: 'Merit General',
    documentsVerified: true,
    appliedDate: '2026-03-01',
    allottedQuota: 'Open All-India Merit',
    remarks: 'Candidate confirmed seat in Round 1 seat matrix.',
  },
  {
    id: 'adm_2026_002',
    applicationNo: 'APP-2026-8802',
    applicantName: 'Nikhil Rathi',
    email: 'nikhil.rathi@yahoo.com',
    phone: '+91 98100 44556',
    programApplied: 'B.Tech Electronics & VLSI Systems',
    departmentId: 'dept_ece',
    entranceScore: 92.1,
    qualifyingPercentage: 91.2,
    status: 'DOCUMENT_VERIFIED',
    category: 'OBC-NCL',
    documentsVerified: true,
    appliedDate: '2026-03-02',
    allottedQuota: 'State Quota Tier 1',
    remarks: 'Awaiting tuition deposit clearance.',
  },
  {
    id: 'adm_2026_003',
    applicationNo: 'APP-2026-8803',
    applicantName: 'Priya Nambiar',
    email: 'priya.n@outlook.com',
    phone: '+91 94460 77889',
    programApplied: 'M.Tech Cyber-Physical Systems',
    departmentId: 'dept_cs',
    entranceScore: 89.6,
    qualifyingPercentage: 88.0,
    status: 'UNDER_SCRUTINY',
    category: 'General',
    documentsVerified: false,
    appliedDate: '2026-03-04',
    allottedQuota: 'GATE Direct Admission',
    remarks: 'Pending B.Tech degree equivalence certificate.',
  },
  {
    id: 'adm_2026_004',
    applicationNo: 'APP-2026-8804',
    applicantName: 'Vikramaditya Solanki',
    email: 'vikram.solanki@rediffmail.com',
    phone: '+91 97654 33221',
    programApplied: 'B.Tech Mechanical & Mechatronics',
    departmentId: 'dept_mech',
    entranceScore: 78.5,
    qualifyingPercentage: 82.4,
    status: 'SUBMITTED',
    category: 'General',
    documentsVerified: false,
    appliedDate: '2026-03-05',
    allottedQuota: 'Institutional Merit',
  },
];

export const seedCourses: CourseStructure[] = [
  {
    id: 'crs_001',
    code: 'CS601',
    title: 'Distributed Systems & Cloud Computing',
    department: 'Computer Science & Engineering',
    departmentId: 'dept_cs',
    semester: 6,
    credits: 4,
    lectureHours: 3,
    tutorialHours: 1,
    practicalHours: 2,
    facultyInCharge: 'Dr. Rajesh Nair',
    leadFaculty: 'Dr. Rajesh Nair',
    syllabusOutline: 'Consensus algorithms, Paxos, Raft, Vector clocks, MapReduce, Containerization.',
    description: 'Comprehensive study of distributed architectures, consistency models, Byzantine fault tolerance, and scalable cloud virtualization frameworks.',
    modules: [
      {
        title: 'Distributed System Foundations & Time Synchronization',
        hours: 12,
        topics: ['Lamport Timestamps', 'Vector Clocks', 'NTP Protocol', 'Distributed Snapshots'],
      },
      {
        title: 'Consensus Protocols & Fault Tolerance',
        hours: 14,
        topics: ['Byzantine Agreement', 'Paxos Algorithm', 'Raft Consensus', 'Leader Election'],
      },
      {
        title: 'Distributed Storage & Cloud Orchestration',
        hours: 14,
        topics: ['MapReduce', 'Cassandra/Dynamo DHT', 'Kubernetes Pod Scheduling', 'Container Networking'],
      },
    ],
    arrearDetails: {
      arrearEligibilityCriteria: 'Candidate must have minimum 30% internal continuous evaluation score and attended at least 4 remedial mentor clinics.',
      arrearExamFormat: 'Special Re-Sit Written Paper (70 Marks) + Practical Viva Voce (30 Marks)',
      arrearPassingThreshold: 40,
      arrearFocusTopics: ['Raft State Transitions', 'Vector Clock Updates', 'Consistent Hashing & Partitioning'],
      specialRemedialSchedule: 'Every Saturday 02:00 PM – 04:00 PM (Lab Turing-4)',
      facultyCoordinator: 'Dr. Rajesh Nair',
      registeredArrearCandidates: 3,
      notes: 'Eligible for backlog special exam scheduled before odd-semester commencement.',
    },
  },
  {
    id: 'crs_002',
    code: 'CS602',
    title: 'Compiler Construction & Optimization',
    department: 'Computer Science & Engineering',
    departmentId: 'dept_cs',
    semester: 6,
    credits: 4,
    lectureHours: 3,
    tutorialHours: 1,
    practicalHours: 2,
    facultyInCharge: 'Dr. P. Sundaram',
    leadFaculty: 'Dr. P. Sundaram',
    syllabusOutline: 'Lexical analysis, LALR parsers, SSA intermediate representation, register allocation.',
    description: 'Theory and design of modern optimizing compilers: lexing, syntax-directed translation, control flow analysis, and SSA machine code generation.',
    modules: [
      {
        title: 'Front-End Syntax & Parsing Techniques',
        hours: 14,
        topics: ['Regular Expressions to DFA', 'LL(1) First & Follow Sets', 'LR(0) and LALR(1) Parsing Tables'],
      },
      {
        title: 'Intermediate Representations & Semantic Analysis',
        hours: 12,
        topics: ['Type Checking Algorithms', 'Three-Address Code', 'Static Single Assignment (SSA)'],
      },
      {
        title: 'Code Optimization & Register Allocation',
        hours: 14,
        topics: ['Common Subexpression Elimination', 'Loop Invariant Motion', 'Graph Coloring Register Allocation'],
      },
    ],
    arrearDetails: {
      arrearEligibilityCriteria: 'Course enrollment in previous cycle with completed lab assignment submissions.',
      arrearExamFormat: '100-Mark Theory Examination covering Modules 1, 2, and 3',
      arrearPassingThreshold: 40,
      arrearFocusTopics: ['LALR(1) Table Construction', 'SSA Form Conversion', 'Graph Coloring Register Allocation'],
      specialRemedialSchedule: 'Every Friday 04:00 PM – 05:30 PM (Hall B-201)',
      facultyCoordinator: 'Dr. P. Sundaram',
      registeredArrearCandidates: 2,
      notes: 'Remedial tutorials mandatory for final arrear hall ticket release.',
    },
  },
  {
    id: 'crs_003',
    code: 'EC401',
    title: 'Digital Signal Processing & Architectures',
    department: 'Electronics & Communication',
    departmentId: 'dept_ece',
    semester: 4,
    credits: 4,
    lectureHours: 3,
    tutorialHours: 0,
    practicalHours: 2,
    facultyInCharge: 'Prof. Evelyn Vance',
    leadFaculty: 'Prof. Evelyn Vance',
    syllabusOutline: 'DFT, FFT, IIR/FIR filter synthesis, fixed-point DSP microarchitectures.',
    description: 'Discrete-time signals and systems, Z-transforms, efficient FFT computation, and digital filter realization on modern DSP processors.',
    modules: [
      {
        title: 'Discrete Fourier Transform & FFT Algorithms',
        hours: 14,
        topics: ['DFT Properties', 'Radix-2 Decimation in Time/Frequency', 'Circular Convolution'],
      },
      {
        title: 'Digital Filter Design (IIR and FIR)',
        hours: 14,
        topics: ['Bilinear Transformation', 'Chebyshev & Butterworth Filters', 'Windowing Techniques (Hamming, Hanning)'],
      },
      {
        title: 'DSP Hardware Architectures & Finite Wordlength',
        hours: 12,
        topics: ['Fixed vs Floating Point DSP', 'MAC Units & Pipelining', 'Quantization Noise Analysis'],
      },
    ],
    arrearDetails: {
      arrearEligibilityCriteria: 'Formal registration with Examination Branch before statutory deadline.',
      arrearExamFormat: 'Comprehensive 80-Mark Theory Paper + 20-Mark MATLAB Simulation Viva',
      arrearPassingThreshold: 40,
      arrearFocusTopics: ['Radix-2 DIT-FFT Butterfly Diagrams', 'Bilinear Transform Filter Mapping', 'Quantization Error Calculations'],
      specialRemedialSchedule: 'Every Thursday 03:30 PM – 05:00 PM (DSP Lab 102)',
      facultyCoordinator: 'Prof. Evelyn Vance',
      registeredArrearCandidates: 4,
      notes: 'Clearance allows student promotion to 5th semester advanced core tracks.',
    },
  },
];

export const seedTimetable: TimetableSlot[] = [
  {
    id: 'tt_01',
    day: 'Monday',
    startTime: '09:00 AM',
    endTime: '10:00 AM',
    courseCode: 'CS601',
    subject: 'Distributed Systems & Cloud Computing',
    faculty: 'Dr. Rajesh Nair',
    room: 'Hall B-201',
    batch: 'Batch CSE-A (Sem 6)',
  },
  {
    id: 'tt_02',
    day: 'Monday',
    startTime: '10:15 AM',
    endTime: '11:15 AM',
    courseCode: 'CS602',
    subject: 'Compiler Construction',
    faculty: 'Dr. P. Sundaram',
    room: 'Hall B-201',
    batch: 'Batch CSE-A (Sem 6)',
  },
  {
    id: 'tt_03',
    day: 'Monday',
    startTime: '11:30 AM',
    endTime: '01:30 PM',
    courseCode: 'CS601L',
    subject: 'Distributed Systems Cloud Laboratory',
    faculty: 'Dr. Rajesh Nair',
    room: 'Lab Turing-4',
    batch: 'Batch CSE-A1',
  },
  {
    id: 'tt_04',
    day: 'Tuesday',
    startTime: '09:00 AM',
    endTime: '10:00 AM',
    courseCode: 'EC401',
    subject: 'Digital Signal Processing',
    faculty: 'Prof. Evelyn Vance',
    room: 'Hall E-102',
    batch: 'Batch ECE-B (Sem 4)',
  },
];

export const seedAttendance: AttendanceSummary[] = [
  {
    id: 'att_01',
    courseCode: 'CS601',
    courseName: 'Distributed Systems',
    department: 'Computer Science & Engineering',
    semester: 6,
    totalLectures: 38,
    averageAttendance: 89.2,
    defaultersCount: 4,
  },
  {
    id: 'att_02',
    courseCode: 'CS602',
    courseName: 'Compiler Construction',
    department: 'Computer Science & Engineering',
    semester: 6,
    totalLectures: 36,
    averageAttendance: 92.1,
    defaultersCount: 2,
  },
  {
    id: 'att_03',
    courseCode: 'EC401',
    courseName: 'Digital Signal Processing',
    department: 'Electronics & Communication',
    semester: 4,
    totalLectures: 40,
    averageAttendance: 78.4,
    defaultersCount: 11,
  },
];

export const seedAttendanceSessions: AttendanceSessionRecord[] = [
  {
    id: 'att_sess_01',
    courseCode: 'CS601',
    courseName: 'Distributed Systems',
    department: 'Computer Science & Engineering',
    semester: 6,
    division: 'A',
    facultyId: 'user_faculty_cse',
    facultyName: 'Dr. P. Sundaram',
    hall: 'LH-302',
    date: '2026-03-12',
    timeSlot: '10:00 AM - 11:00 AM',
    topic: 'Lecture 38: Byzantine Fault Tolerance & Paxos Protocols',
    totalStudents: 30,
    presentCount: 28,
    absentCount: 2,
    lateCount: 0,
    turnoutPercentage: 93.3,
    timestamp: '2026-03-12 10:55:00',
    isSealed: true,
    ledgerTxId: 'TX-ATT-20260312-CS601-038',
    records: [
      {
        studentId: 'stu_001',
        rollNo: '2301031800159',
        name: 'Aarav Sharma',
        status: 'PRESENT',
        method: 'RFID_AUTO',
        rfidTimestamp: '10:01:22 AM',
        rfidTagId: 'RFID-CS-042',
      },
      {
        studentId: 'stu_002',
        rollNo: '2301031800160',
        name: 'Ananya Iyer',
        status: 'PRESENT',
        method: 'RFID_AUTO',
        rfidTimestamp: '09:58:45 AM',
        rfidTagId: 'RFID-CS-088',
      },
      {
        studentId: 'stu_003',
        rollNo: '2301031800161',
        name: 'Ishaan Verma',
        status: 'ABSENT',
        method: 'RFID_AUTO',
      },
    ],
  },
  {
    id: 'att_sess_02',
    courseCode: 'CS602',
    courseName: 'Compiler Construction',
    department: 'Computer Science & Engineering',
    semester: 6,
    division: 'A',
    facultyId: 'user_faculty_cse',
    facultyName: 'Dr. P. Sundaram',
    hall: 'LH-305',
    date: '2026-03-11',
    timeSlot: '11:15 AM - 12:15 PM',
    topic: 'Lecture 36: LALR(1) Parsing Table Construction & Shift-Reduce Conflicts',
    totalStudents: 28,
    presentCount: 26,
    absentCount: 2,
    lateCount: 1,
    turnoutPercentage: 92.9,
    timestamp: '2026-03-11 12:10:00',
    isSealed: true,
    ledgerTxId: 'TX-ATT-20260311-CS602-036',
    records: [
      {
        studentId: 'stu_001',
        rollNo: '2301031800159',
        name: 'Aarav Sharma',
        status: 'PRESENT',
        method: 'RFID_AUTO',
        rfidTimestamp: '11:14:10 AM',
        rfidTagId: 'RFID-CS-042',
      },
      {
        studentId: 'stu_002',
        rollNo: '2301031800160',
        name: 'Ananya Iyer',
        status: 'PRESENT',
        method: 'RFID_AUTO',
        rfidTimestamp: '11:12:30 AM',
        rfidTagId: 'RFID-CS-088',
      },
    ],
  },
];

export const seedMarks: ExaminationMark[] = [
  {
    id: 'mark_001',
    studentId: 'stu_001',
    rollNo: '2301031800159',
    studentName: 'Aarav Sharma',
    courseCode: 'CS601',
    courseName: 'Distributed Systems',
    semester: 6,
    internalMarks: 28,
    maxInternal: 30,
    theoryMarks: 65,
    maxTheory: 70,
    totalMarks: 93,
    maxTotal: 100,
    grade: 'A+',
    status: 'VALID',
    evaluator: 'Dr. Rajesh Nair',
    lastUpdated: '2026-03-10 14:30',
  },
  {
    id: 'mark_002',
    studentId: 'stu_002',
    rollNo: '21CS088',
    studentName: 'Ananya Iyer',
    courseCode: 'CS601',
    courseName: 'Distributed Systems',
    semester: 6,
    internalMarks: 30,
    maxInternal: 30,
    theoryMarks: 69,
    maxTheory: 70,
    totalMarks: 99,
    maxTotal: 100,
    grade: 'O',
    status: 'VALID',
    evaluator: 'Dr. Rajesh Nair',
    lastUpdated: '2026-03-10 14:30',
  },
  {
    id: 'mark_003',
    studentId: 'stu_005',
    rollNo: '21CS112',
    studentName: 'Devansh Kulkarni',
    courseCode: 'CS601',
    courseName: 'Distributed Systems',
    semester: 6,
    internalMarks: 18,
    maxInternal: 30,
    theoryMarks: 74, // Intentional violation of 70 ceiling
    maxTheory: 70,
    totalMarks: 92,
    maxTotal: 100,
    grade: 'CRITICAL',
    status: 'CRITICAL',
    validationMessage: 'Theory marks (74) exceed statutory maximum ceiling of 70!',
    evaluator: 'Dr. Rajesh Nair',
    lastUpdated: '2026-03-10 14:30',
  },
];

export const seedResources: ResourceUploadItem[] = [
  {
    id: 'res_001',
    title: 'Unit 1-3: Paxos & Raft Formal Verification Handouts',
    category: 'Lecture Notes',
    resourceType: 'Lecture Notes',
    description: 'Comprehensive slides and mathematical proofs for consensus safety invariants in distributed clusters.',
    academicYear: '2025-2026',
    term: 'Spring 2026',
    department: 'Computer Science & Engineering',
    departmentId: 'dept_cs',
    course: 'B.Tech Computer Science & Engineering',
    courseCode: 'BTECH-CSE',
    courseName: 'Distributed Systems & Cloud Computing',
    subject: 'Distributed Systems & Cloud Computing',
    subjectCode: 'CS601',
    division: 'Division A',
    batch: '2021-2025',
    semester: 6,
    driveUrl: 'https://drive.google.com/file/d/paxos_raft_core.pdf',
    fileUrl: 'https://drive.google.com/file/d/paxos_raft_core.pdf',
    fileSize: '3.4 MB',
    fileType: 'PDF',
    isGlobal: false,
    priority: 'NORMAL',
    status: 'PUBLISHED',
    uploadedBy: 'Dr. Rajesh Nair',
    uploadedById: 'user_faculty_cse',
    uploadedAt: '2026-03-08 10:15',
    targetStudentsCount: 64,
    downloadCount: 58,
    viewCount: 142,
    tags: ['Consensus', 'Raft', 'Paxos', 'Cloud'],
  },
  {
    id: 'res_002',
    title: 'Laboratory Manual: LLVM Compiler Passes & IR Generation',
    category: 'Learning Materials',
    resourceType: 'Learning Materials',
    description: 'Practical workbook with C++ AST visitors, SSA transformation templates, and dead code elimination test harness.',
    academicYear: '2025-2026',
    term: 'Spring 2026',
    department: 'Computer Science & Engineering',
    departmentId: 'dept_cs',
    course: 'B.Tech Computer Science & Engineering',
    courseCode: 'BTECH-CSE',
    courseName: 'Compiler Construction & Optimization',
    subject: 'Compiler Construction & Optimization',
    subjectCode: 'CS602',
    division: 'Division A',
    batch: '2021-2025',
    semester: 6,
    driveUrl: 'https://drive.google.com/file/d/llvm_passes_v3.pdf',
    fileUrl: 'https://drive.google.com/file/d/llvm_passes_v3.pdf',
    fileSize: '6.8 MB',
    fileType: 'PDF',
    isGlobal: false,
    priority: 'NORMAL',
    status: 'PUBLISHED',
    uploadedBy: 'Dr. P. Sundaram',
    uploadedById: 'user_faculty_cse',
    uploadedAt: '2026-03-09 11:40',
    targetStudentsCount: 64,
    downloadCount: 62,
    viewCount: 198,
    tags: ['LLVM', 'Compiler', 'IR', 'C++'],
  },
  {
    id: 'res_003',
    title: 'Spring 2026 Mid-Term Examination Schedule & Hall Allocation',
    category: 'Announcements',
    resourceType: 'Announcements',
    description: 'Statutory examination schedule, room assignments, and mandatory student ID verification directives.',
    academicYear: '2025-2026',
    term: 'Spring 2026',
    department: 'All Departments',
    departmentId: 'dept_all',
    course: 'All Undergraduate Programs',
    courseCode: 'ALL',
    courseName: 'Institutional Examination Board',
    subject: 'All Subjects',
    subjectCode: 'ALL',
    division: 'ALL',
    batch: 'ALL',
    semester: 6,
    driveUrl: 'https://drive.google.com/file/d/midterm_circular_2026.pdf',
    fileUrl: 'https://drive.google.com/file/d/midterm_circular_2026.pdf',
    fileSize: '1.2 MB',
    fileType: 'PDF',
    announcementContent: 'Mid-term examinations will commence on April 15, 2026. All candidates must report to their allotted examination halls 20 minutes prior to session commencement with institutional RFID smart cards.',
    isGlobal: true,
    priority: 'STATUTORY',
    status: 'PUBLISHED',
    uploadedBy: 'Prof. Evelyn Vance',
    uploadedById: 'user_dean_academics',
    uploadedAt: '2026-03-11 09:00',
    targetStudentsCount: 1240,
    downloadCount: 840,
    viewCount: 2310,
    tags: ['Examination', 'Statutory', 'Circular', 'Mid-Term'],
  },
  {
    id: 'res_004',
    title: 'Distributed Hash Tables (Chord / Kademlia) Problem Set',
    category: 'Learning Materials',
    resourceType: 'Learning Materials',
    description: 'Weekly algorithmic assignment on consistent hashing finger tables and stabilization routines.',
    academicYear: '2025-2026',
    term: 'Spring 2026',
    department: 'Computer Science & Engineering',
    departmentId: 'dept_cs',
    course: 'B.Tech Computer Science & Engineering',
    courseCode: 'BTECH-CSE',
    courseName: 'Distributed Systems & Cloud Computing',
    subject: 'Distributed Systems & Cloud Computing',
    subjectCode: 'CS601',
    division: 'Division A',
    batch: '2021-2025',
    semester: 6,
    driveUrl: 'https://drive.google.com/file/d/dht_kademlia_problems.pdf',
    fileUrl: 'https://drive.google.com/file/d/dht_kademlia_problems.pdf',
    fileSize: '1.8 MB',
    fileType: 'PDF',
    isGlobal: false,
    priority: 'NORMAL',
    status: 'PUBLISHED',
    uploadedBy: 'Dr. Rajesh Nair',
    uploadedById: 'user_faculty_cse',
    uploadedAt: '2026-03-11 16:20',
    targetStudentsCount: 64,
    downloadCount: 41,
    viewCount: 110,
    tags: ['P2P', 'DHT', 'Chord', 'Kademlia'],
  },
  {
    id: 'res_005',
    title: 'Digital Signal Processing: FIR & IIR Filter Design Notes',
    category: 'Lecture Notes',
    resourceType: 'Lecture Notes',
    description: 'Bilinear transformation and Chebyshev filter design notes with MATLAB simulation examples.',
    academicYear: '2025-2026',
    term: 'Spring 2026',
    department: 'Electronics & Communication',
    departmentId: 'dept_ece',
    course: 'B.Tech Electronics & Communication',
    courseCode: 'BTECH-ECE',
    courseName: 'Digital Signal Processing & Architectures',
    subject: 'Digital Signal Processing & Architectures',
    subjectCode: 'EC401',
    division: 'Division A',
    batch: '2022-2026',
    semester: 4,
    driveUrl: 'https://drive.google.com/file/d/dsp_filter_design.pdf',
    fileUrl: 'https://drive.google.com/file/d/dsp_filter_design.pdf',
    fileSize: '4.2 MB',
    fileType: 'PDF',
    isGlobal: false,
    priority: 'NORMAL',
    status: 'PUBLISHED',
    uploadedBy: 'Prof. Evelyn Vance',
    uploadedById: 'user_dean_academics',
    uploadedAt: '2026-03-10 14:00',
    targetStudentsCount: 58,
    downloadCount: 39,
    viewCount: 95,
    tags: ['DSP', 'IIR', 'FIR', 'Filters'],
  },
  {
    id: 'res_006',
    title: 'Urgent: Submission of Semester VI Project Proposal Synopses',
    category: 'Announcements',
    resourceType: 'Announcements',
    description: 'Mandatory deadline notice for all CSE B.Tech Semester VI capstone project proposal submissions.',
    academicYear: '2025-2026',
    term: 'Spring 2026',
    department: 'Computer Science & Engineering',
    departmentId: 'dept_cs',
    course: 'B.Tech Computer Science & Engineering',
    courseCode: 'BTECH-CSE',
    courseName: 'Capstone Project Phase I',
    subject: 'Capstone Project Phase I',
    subjectCode: 'CS603',
    division: 'ALL',
    batch: '2021-2025',
    semester: 6,
    driveUrl: 'https://drive.google.com/file/d/project_proposal_guidelines.pdf',
    fileUrl: 'https://drive.google.com/file/d/project_proposal_guidelines.pdf',
    fileSize: '0.8 MB',
    fileType: 'PDF',
    announcementContent: 'All Semester VI CSE students must submit their finalized capstone project proposals signed by their faculty mentors before March 25, 2026. Late submissions will result in grade penalties.',
    isGlobal: false,
    priority: 'URGENT',
    status: 'PUBLISHED',
    uploadedBy: 'Dr. P. Sundaram',
    uploadedById: 'user_faculty_cse',
    uploadedAt: '2026-03-12 08:30',
    targetStudentsCount: 128,
    downloadCount: 112,
    viewCount: 340,
    tags: ['Project', 'Capstone', 'Deadline', 'Urgent'],
  },
];

export const seedFees: FeeChallan[] = [
  {
    id: 'fee_001',
    challanNo: 'CH-2026-0914',
    studentId: 'stu_001',
    studentName: 'Aarav Sharma',
    rollNo: '2301031800159',
    semester: 6,
    feeHead: 'Tuition & Academic Facilities Fee',
    totalAmount: 115000,
    paidAmount: 115000,
    balanceAmount: 0,
    dueDate: '2026-01-30',
    status: 'PAID',
    receiptNo: 'REC-2026-8812',
  },
  {
    id: 'fee_002',
    challanNo: 'CH-2026-0915',
    studentId: 'stu_016',
    studentName: 'Rohan Mehra',
    rollNo: '2301041800001',
    semester: 4,
    feeHead: 'Tuition & Examination Fee',
    totalAmount: 95000,
    paidAmount: 50000,
    balanceAmount: 45000,
    dueDate: '2026-03-31',
    status: 'PARTIAL',
  },
  {
    id: 'fee_003',
    challanNo: 'CH-2026-0916',
    studentId: 'stu_006',
    studentName: 'Devansh Kulkarni',
    rollNo: '2301031800164',
    semester: 6,
    feeHead: 'Hostel & Mess Charges',
    totalAmount: 62000,
    paidAmount: 0,
    balanceAmount: 62000,
    dueDate: '2026-02-15',
    status: 'OVERDUE',
  },
];

export const seedHostels: HostelRoom[] = [
  {
    id: 'hos_rm_01',
    blockName: 'Kaveri Hall (Senior Boys)',
    roomNo: 'B-302',
    floor: 3,
    capacity: 2,
    occupied: 2,
    occupants: [
      { studentId: 'stu_001', studentName: 'Aarav Sharma', rollNo: '2301031800159', bedNo: 'Bed A' },
      { studentId: 'stu_005', studentName: 'Sameer Sen', rollNo: '2301031800163', bedNo: 'Bed B' },
    ],
    status: 'FULL',
  },
  {
    id: 'hos_rm_02',
    blockName: 'Kaveri Hall (Senior Boys)',
    roomNo: 'B-304',
    floor: 3,
    capacity: 2,
    occupied: 1,
    occupants: [
      { studentId: 'stu_010', studentName: 'Rishi Nambiar', rollNo: '2301031800168', bedNo: 'Bed A' },
    ],
    status: 'AVAILABLE',
  },
  {
    id: 'hos_rm_03',
    blockName: 'Ganga Hall (Girls Hostel)',
    roomNo: 'A-104',
    floor: 1,
    capacity: 2,
    occupied: 2,
    occupants: [
      { studentId: 'stu_002', studentName: 'Ananya Iyer', rollNo: '2301031800160', bedNo: 'Bed A' },
      { studentId: 'stu_003', studentName: 'Ishaan Verma', rollNo: '2301031800161', bedNo: 'Bed B' },
    ],
    status: 'FULL',
  },
  {
    id: 'hos_rm_04',
    blockName: 'Ganga Hall (Girls Hostel)',
    roomNo: 'B-211',
    floor: 2,
    capacity: 3,
    occupied: 1,
    occupants: [
      { studentId: 'stu_018', studentName: 'Kavya Pillai', rollNo: '2301021800001', bedNo: 'Bed A' },
    ],
    status: 'AVAILABLE',
  },
];

export const seedLibrary: LibraryBook[] = [
  {
    id: 'lib_01',
    isbn: '978-0133591620',
    title: 'Designing Data-Intensive Applications',
    author: 'Martin Kleppmann',
    department: 'Computer Science',
    totalCopies: 12,
    availableCopies: 3,
    rackLocation: 'Rack CS-04-B',
    status: 'AVAILABLE',
  },
  {
    id: 'lib_02',
    isbn: '978-0131103627',
    title: 'The C Programming Language (2nd Ed)',
    author: 'Brian W. Kernighan, Dennis M. Ritchie',
    department: 'Computer Science',
    totalCopies: 25,
    availableCopies: 18,
    rackLocation: 'Rack CS-01-A',
    status: 'AVAILABLE',
  },
  {
    id: 'lib_03',
    isbn: '978-0262033848',
    title: 'Introduction to Algorithms (CLRS 3rd Ed)',
    author: 'Thomas H. Cormen et al.',
    department: 'Computer Science & Mathematics',
    totalCopies: 30,
    availableCopies: 0,
    rackLocation: 'Rack CS-02-C',
    status: 'OUT_OF_STOCK',
  },
];

export const seedFaculty: FacultyMember[] = [
  {
    id: 'fac_001',
    employeeId: 'FAC-082',
    name: 'Dr. Rajesh Nair',
    email: 'rnair@nexusuniv.edu',
    department: 'Computer Science & Engineering',
    designation: 'Professor & Head of Department',
    qualifications: 'Ph.D. Distributed Systems (IISc Bangalore)',
    assignedCourses: ['CS601', 'CS804'],
    monthlySalary: 215000,
    biometricActive: true,
    status: 'ACTIVE',
  },
  {
    id: 'fac_002',
    employeeId: 'FAC-014',
    name: 'Prof. Evelyn Vance',
    email: 'evance@nexusuniv.edu',
    department: 'Electronics & Communication',
    designation: 'Professor & Dean Academics',
    qualifications: 'Ph.D. Signal Processing (Stanford Univ)',
    assignedCourses: ['EC401'],
    monthlySalary: 245000,
    biometricActive: true,
    status: 'ACTIVE',
  },
  {
    id: 'fac_003',
    employeeId: 'FAC-099',
    name: 'Dr. P. Sundaram',
    email: 'psundaram@nexusuniv.edu',
    department: 'Computer Science & Engineering',
    designation: 'Associate Professor',
    qualifications: 'Ph.D. Programming Languages (IIT Bombay)',
    assignedCourses: ['CS602'],
    monthlySalary: 165000,
    biometricActive: true,
    status: 'ACTIVE',
  },
];

export const seedNotices: NoticeCircular[] = [
  {
    id: 'not_01',
    circularNo: 'CIRC-2026/041',
    title: 'Mandatory Submission of Re-evaluation Applications for End-Sem V',
    category: 'Examinations',
    targetAudience: 'All Final & Pre-Final Year Students',
    publishedDate: '2026-03-09',
    content: 'Students desiring verification or photocopy of evaluated answer scripts must apply through the COE portal before 20th March 2026.',
    priority: 'High',
    issuer: 'Controller of Examinations',
  },
  {
    id: 'not_02',
    circularNo: 'CIRC-2026/042',
    title: 'Campus Hackathon 2026: Institutional Funding & Industry Mentorship',
    category: 'Academic',
    targetAudience: 'All Registered Students',
    publishedDate: '2026-03-11',
    content: 'The 48-hour Annual Campus Hackathon commences on April 4th. Shortlisted teams will receive ₹50,000 project prototyping grants.',
    priority: 'Standard',
    issuer: 'Dean of Research & Innovation',
  },
];

export const seedDocuments: DocumentVerification[] = [
  {
    id: 'doc_001',
    documentNo: 'DOC-DEG-2025-0019',
    studentId: 'stu_001',
    studentName: 'Aarav Sharma',
    rollNo: '2301031800159',
    docType: 'Semester Grade Transcript',
    sha256Hash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    issuedBy: 'Controller of Examinations',
    issuedDate: '2026-01-15',
    status: 'VERIFIED',
  },
  {
    id: 'doc_002',
    documentNo: 'DOC-DEG-2025-0020',
    studentId: 'stu_002',
    studentName: 'Ananya Iyer',
    rollNo: '2301031800160',
    docType: 'Bonafide Certificate',
    sha256Hash: 'ca978112ca1bbdcafac231b39a23dc4da786eff8147c4e72b9807785afee48bb',
    issuedBy: 'Dean of Student Affairs',
    issuedDate: '2026-02-10',
    status: 'VERIFIED',
  },
];

export const seedSessions: ActiveSession[] = [
  {
    id: 'sess_01',
    userId: 'user_super_admin',
    userName: 'Dr. Aris Thorne',
    role: 'SUPER_ADMIN',
    ipAddress: '192.168.1.105',
    device: 'Apple MacBook Pro M3 Max',
    browser: 'Chrome 122.0.6261 (macOS)',
    location: 'Campus IT Headquarters, Wing A',
    loginTime: 'Today, 08:30 AM',
    lastActive: '12 seconds ago',
    status: 'ACTIVE',
    isCurrentSession: true,
  },
  {
    id: 'sess_02',
    userId: 'user_dean_academics',
    userName: 'Prof. Evelyn Vance',
    role: 'DEAN_ACADEMICS',
    ipAddress: '192.168.1.142',
    device: 'Lenovo ThinkPad X1 Carbon',
    browser: 'Firefox 123.0 (Linux)',
    location: 'Dean Secretariat, Main Quad',
    loginTime: 'Today, 09:12 AM',
    lastActive: '4 minutes ago',
    status: 'ACTIVE',
    isCurrentSession: false,
  },
  {
    id: 'sess_03',
    userId: 'user_hod_cse',
    userName: 'Dr. Rajesh Nair',
    role: 'HOD_CSE',
    ipAddress: '192.168.4.55',
    device: 'Dell Precision Tower 5820',
    browser: 'Chrome 122.0.6261 (Windows 11)',
    location: 'CSE Department Research Lab',
    loginTime: 'Today, 09:45 AM',
    lastActive: '38 minutes ago',
    status: 'LOCKED',
    isCurrentSession: false,
  },
  {
    id: 'sess_04',
    userId: 'user_bursar',
    userName: 'Meera Deshmukh',
    role: 'BURSAR_FINANCE',
    ipAddress: '192.168.2.80',
    device: 'Apple MacBook Air M2',
    browser: 'Safari 17.3 (macOS)',
    location: 'Accounts Branch, Ground Floor',
    loginTime: 'Today, 10:05 AM',
    lastActive: '2 minutes ago',
    status: 'ACTIVE',
    isCurrentSession: false,
  },
];

export const seedAuditLogs: AuditLogEntry[] = [
  {
    id: 'log_01',
    timestamp: '2026-03-12 11:34:02',
    actorId: 'user_coe',
    actorName: 'Dr. S. K. Bhattacharya',
    actorRole: 'COE_OFFICER',
    action: 'COE_LEDGER_INTEGRITY_SCAN',
    entity: 'ExaminationBatch',
    entityId: 'BATCH_CS601_SEM6',
    details: 'Pre-flight acid validator identified 1 critical mark-cap breach in Roll 21CS112.',
    severity: 'WARNING',
    ipAddress: '192.168.3.12',
  },
  {
    id: 'log_02',
    timestamp: '2026-03-12 10:45:18',
    actorId: 'user_super_admin',
    actorName: 'Dr. Aris Thorne',
    actorRole: 'SUPER_ADMIN',
    action: 'RBAC_SECURITY_POLICY_UPDATE',
    entity: 'IAMPolicy',
    entityId: 'POL_MFA_ENFORCE_FACULTY',
    details: 'Campus-wide mandatory TOTP MFA enforcement successfully deployed to all 420 faculty credentials.',
    severity: 'INFO',
    ipAddress: '192.168.1.105',
  },
  {
    id: 'log_03',
    timestamp: '2026-03-12 09:12:44',
    actorId: 'user_bursar',
    actorName: 'Meera Deshmukh',
    actorRole: 'BURSAR_FINANCE',
    action: 'FEE_RECEIPT_COUNTERSIGNED',
    entity: 'FeeChallan',
    entityId: 'CH-2026-0914',
    details: 'Issued digital receipt REC-2026-8812 for tuition fee clearance of ₹1,15,000 for student Aarav Sharma (2301031800159).',
    severity: 'INFO',
    ipAddress: '192.168.2.80',
  },
];
